In [5]:
import pandas as pd

# Import our input dataset
fire_df = pd.read_csv('../Resources/wildfire_v2_clean_data.csv')
fire_df

,fire_size,fire_size_class,fire_cause,latitude,longitude,state,discovery_month,discovery_date,discovery_year,Vegetation,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
0,10.0,C,Missing/Undefined,18.105072,-66.753044,PR,Feb,1/12/2007,2007,12,...,3.250413,78.216590,76.793750,76.381579,78.724370,0.0,0.0,0.0,0.0,0.017923
1,3.0,B,Arson,35.038330,-87.610000,TN,Dec,11/11/2006,2006,15,...,2.122320,70.840000,65.858911,55.505882,81.682678,59.8,8.4,0.0,86.8,0.184355
2,60.0,C,Arson,34.947800,-88.722500,MS,Feb,1/30/2004,2004,16,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
3,1.0,B,Debris Burning,39.641400,-119.308300,NV,Jun,5/7/2005,2005,0,...,0.000000,44.778429,37.140811,35.353846,0.000000,10.4,7.2,0.0,0.0,0.487447
4,2.0,B,Miscellaneous,30.700600,-90.591400,LA,Sep,8/23/1999,1999,12,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.214633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55362,6289.0,G,Missing/Undefined,39.180000,-96.784167,KS,Oct,9/15/2015,2015,0,...,3.804803,65.671410,61.839572,54.625698,55.042092,35.4,8.2,0.0,249.0,0.331501
55363,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,Sep,8/10/2015,2015,0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55364,5702.0,G,Arson,37.262607,-119.511139,CA,Jul,6/25/2015,2015,0,...,2.529158,43.755556,43.755556,44.443975,35.924406,0.0,0.0,0.0,0.0,0.097682
55365,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,Jul,7/1/2015,2015,15,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206
55366,76067.0,G,Missing/Undefined,38.843988,-122.759707,CA,Sep,8/13/2015,2015,0,...,1.208073,50.521912,46.310627,37.178571,58.063802,0.3,0.3,0.0,18.8,0.167305

In [56]:
fire_clean_df1=fire_df.loc[(fire_df["Temp_pre_30"]!=0)&
                         (fire_df["Temp_pre_15"]!=0)&
                         (fire_df["Temp_pre_7"]!=0)&
                         (fire_df["Temp_cont"]!=0)&
                         (fire_df["Wind_pre_30"]!=0)&
                         (fire_df["Wind_pre_15"]!=0)&
                         (fire_df["Wind_pre_7"]!=0)&
                         (fire_df["Wind_cont"]!=0)&
                         (fire_df["Hum_pre_30"]!=0)&
                         (fire_df["Hum_pre_15"]!=0)&
                         (fire_df["Hum_pre_7"]!=0)&
                         (fire_df["Hum_cont"]!=0)&
                         (fire_df["Prec_pre_30"]!=0)&
                          (fire_df["Prec_pre_15"]!=0)&
                          (fire_df["Prec_pre_7"]!=0)&
                          (fire_df["Prec_cont"]!=0)]
fire_clean_df1

,fire_size,fire_size_class,fire_cause,latitude,longitude,state,discovery_month,discovery_date,discovery_year,Vegetation,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
2,60.0,C,Arson,34.947800,-88.722500,MS,Feb,1/30/2004,2004,16,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
4,2.0,B,Miscellaneous,30.700600,-90.591400,LA,Sep,8/23/1999,1999,12,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.214633
5,1.0,B,Debris Burning,32.063900,-82.417800,GA,Mar,2/20/1999,1999,12,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.139643
7,1.0,B,Campfire,30.904720,-93.557500,TX,Nov,10/13/2005,2005,12,...,2.148857,72.899478,75.061381,77.924623,70.732911,28.4,27.5,1.2,55.4,0.241894
10,8.3,B,Debris Burning,30.845339,-83.127987,GA,Mar,2/4/2010,2010,12,...,1.750701,71.260870,69.281030,64.797980,73.072072,76.3,26.2,8.4,40.5,0.146888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55354,4000.0,F,Missing/Undefined,33.421111,-117.503333,CA,Apr,3/29/2015,2015,16,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.128217
55356,4336.0,F,Lightning,34.316000,-112.268300,AZ,Aug,7/3/2015,2015,16,...,3.193614,45.053836,46.349030,40.786982,49.818887,86.9,78.8,6.9,41.0,0.192487
55357,4856.0,F,Lightning,29.616667,-94.273333,TX,Jul,6/30/2015,2015,12,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.548644
55363,70868.0,G,Missing/Undefined,38.342719,-120.695967,CA,Sep,8/10/2015,2015,0,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.124683
55365,3261.0,F,Miscellaneous,40.604300,-123.080450,CA,Jul,7/1/2015,2015,15,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,-1.0,0.178206

In [58]:
fire_clean_df2=fire_clean_df1.loc[(fire_df["Temp_pre_30"]!=-1)&
                         (fire_df["Temp_pre_15"]!=-1)&
                         (fire_df["Temp_pre_7"]!=-1)&
                         (fire_df["Temp_cont"]!=-1)&
                         (fire_df["Wind_pre_30"]!=-1)&
                         (fire_df["Wind_pre_15"]!=-1)&
                         (fire_df["Wind_pre_7"]!=-1)&
                         (fire_df["Wind_cont"]!=-1)&
                         (fire_df["Hum_pre_30"]!=-1)&
                         (fire_df["Hum_pre_15"]!=-1)&
                         (fire_df["Hum_pre_7"]!=-1)&
                         (fire_df["Hum_cont"]!=-1)&
                         (fire_df["Prec_pre_30"]!=-1)&
                          (fire_df["Prec_pre_15"]!=-1)&
                          (fire_df["Prec_pre_7"]!=-1)&
                          (fire_df["Prec_cont"]!=-1)]
fire_clean_df2

,fire_size,fire_size_class,fire_cause,latitude,longitude,state,discovery_month,discovery_date,discovery_year,Vegetation,...,Wind_cont,Hum_pre_30,Hum_pre_15,Hum_pre_7,Hum_cont,Prec_pre_30,Prec_pre_15,Prec_pre_7,Prec_cont,remoteness
2,60.0,C,Arson,34.947800,-88.722500,MS,Feb,1/30/2004,2004,16,...,3.369050,75.531629,75.868613,76.812834,65.063800,168.8,42.2,18.1,124.5,0.194544
7,1.0,B,Campfire,30.904720,-93.557500,TX,Nov,10/13/2005,2005,12,...,2.148857,72.899478,75.061381,77.924623,70.732911,28.4,27.5,1.2,55.4,0.241894
10,8.3,B,Debris Burning,30.845339,-83.127987,GA,Mar,2/4/2010,2010,12,...,1.750701,71.260870,69.281030,64.797980,73.072072,76.3,26.2,8.4,40.5,0.146888
28,1.0,B,Miscellaneous,42.731934,-77.905976,NY,Apr,3/4/2010,2010,4,...,2.872771,68.640553,69.556263,63.966184,59.956798,52.9,38.4,2.3,30.5,0.094048
29,20.0,C,Arson,31.122200,-88.099400,AL,Jun,5/5/2000,2000,12,...,2.623313,73.717979,74.603325,69.440594,77.471227,93.7,85.3,41.4,154.3,0.191512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55331,3082.0,F,Lightning,48.383600,-117.891900,WA,Aug,7/15/2015,2015,15,...,2.918241,37.301713,36.085561,40.526012,49.762009,2.0,2.0,2.0,9.2,0.124757
55339,4800.0,F,Equipment Use,45.135700,-99.908700,SD,Apr,3/2/2015,2015,9,...,5.456159,58.984906,61.466667,60.994872,56.239420,4.4,4.4,4.1,12.2,0.182660
55340,5100.0,G,Equipment Use,45.069700,-99.821100,SD,Apr,3/3/2015,2015,9,...,5.316949,57.976101,59.909524,58.129730,56.989091,4.4,4.4,4.1,12.7,0.184977
55341,17823.0,G,Campfire,44.834600,-117.220600,OR,Sep,8/13/2015,2015,15,...,2.292956,55.009259,62.368700,67.266304,58.917679,10.4,10.4,9.4,8.6,0.088821
55356,4336.0,F,Lightning,34.316000,-112.268300,AZ,Aug,7/3/2015,2015,16,...,3.193614,45.053836,46.349030,40.786982,49.818887,86.9,78.8,6.9,41.0,0.192487

In [96]:
fire_clean_df2.columns

Index(['fire_size', 'fire_size_class', 'fire_cause', 'latitude', 'longitude',
       'state', 'discovery_month', 'discovery_date', 'discovery_year',
       'Vegetation', 'fire_mag', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7',
       'Temp_cont', 'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont',
       'Hum_pre_30', 'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30',
       'Prec_pre_15', 'Prec_pre_7', 'Prec_cont', 'remoteness'],
      dtype='object')

In [64]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.svm import SVC
import pandas as pd
import tensorflow as tf

In [107]:
fire_clean_df=fire_clean_df2.drop(columns=["discovery_date","fire_size_class",
                                           "fire_mag","state","discovery_year","remoteness"])
fire_clean_df.columns

Index(['fire_size', 'fire_cause', 'latitude', 'longitude', 'discovery_month',
       'Vegetation', 'Temp_pre_30', 'Temp_pre_15', 'Temp_pre_7', 'Temp_cont',
       'Wind_pre_30', 'Wind_pre_15', 'Wind_pre_7', 'Wind_cont', 'Hum_pre_30',
       'Hum_pre_15', 'Hum_pre_7', 'Hum_cont', 'Prec_pre_30', 'Prec_pre_15',
       'Prec_pre_7', 'Prec_cont'],
      dtype='object')

In [108]:
# Generate our categorical variable list
fire_cat = fire_clean_df.dtypes[fire_df.dtypes == "object"].index.tolist()

# Check the number of unique values in each column
fire_clean_df[fire_cat].nunique()

fire_cause         13
discovery_month    12
dtype: int64

In [109]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(fire_clean_df[fire_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(fire_cat)
encode_df.head()

,fire_cause_Arson,fire_cause_Campfire,fire_cause_Children,fire_cause_Debris Burning,fire_cause_Equipment Use,fire_cause_Fireworks,fire_cause_Lightning,fire_cause_Miscellaneous,fire_cause_Missing/Undefined,fire_cause_Powerline,...,discovery_month_Dec,discovery_month_Feb,discovery_month_Jan,discovery_month_Jul,discovery_month_Jun,discovery_month_Mar,discovery_month_May,discovery_month_Nov,discovery_month_Oct,discovery_month_Sep
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [110]:
# Merge one-hot encoded features and drop the originals
x_df = fire_clean_df.merge(encode_df,left_index=True, right_index=True)
x_df = x_df.drop(fire_cat,1)
x_df.head()

,fire_size,latitude,longitude,Vegetation,Temp_pre_30,Temp_pre_15,Temp_pre_7,Temp_cont,Wind_pre_30,Wind_pre_15,...,discovery_month_Dec,discovery_month_Feb,discovery_month_Jan,discovery_month_Jul,discovery_month_Jun,discovery_month_Mar,discovery_month_May,discovery_month_Nov,discovery_month_Oct,discovery_month_Sep
2,60.0,34.947800,-88.722500,16,4.971930,5.782766,5.558750,13.696600,3.364499,2.923830,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,1.0,30.904720,-93.557500,12,16.851939,16.997783,20.434783,11.985560,1.331257,1.472949,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,8.3,30.845339,-83.127987,12,8.410983,9.007193,8.209000,14.328047,1.988671,1.745012,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
28,1.0,42.731934,-77.905976,4,5.181473,6.003609,7.773430,11.375329,3.011636,3.221656,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
29,20.0,31.122200,-88.099400,12,24.566175,25.548871,25.232870,25.610425,3.414215,3.272371,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [111]:
# Remove target from features data
import numpy as np
y = np.reshape(x_df.fire_size.values,(-1,1))
X = pd.DataFrame(x_df.drop(columns=["fire_size"]))
# Split training/test datasets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [112]:
y.shape

(950, 1)

In [113]:
X_test_scaled.shape

(238, 44)

In [114]:
# Create a random forest regressor.
rf_model = RandomForestRegressor(n_estimators=100, random_state=2)

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

C:\Users\k9350\anaconda3\envs\mlenv\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """

In [115]:
# Evaluate the model
y_pred = rf_model.predict(X_test_scaled)
from sklearn.metrics import accuracy_score
rf_model.score(X_test_scaled, y_test)

-0.0128069985694792

In [86]:
help(rf_model.score)

Help on method score in module sklearn.base:

score(X, y, sample_weight=None) method of sklearn.ensemble._forest.RandomForestRegressor instance
    Return the coefficient of determination :math:`R^2` of the
    prediction.

    The coefficient :math:`R^2` is defined as :math:`(1 - \frac{u}{v})`,
    where :math:`u` is the residual sum of squares ``((y_true - y_pred)
    ** 2).sum()`` and :math:`v` is the total sum of squares ``((y_true -
    y_true.mean()) ** 2).sum()``. The best possible score is 1.0 and it
    can be negative (because the model can be arbitrarily worse). A
    constant model that always predicts the expected value of `y`,
    disregarding the input features, would get a :math:`R^2` score of
    0.0.

    Parameters
    ----------
    X : array-like of shape (n_samples, n_features)
        Test samples. For some estimators this may be a precomputed
        kernel matrix or a list of generic objects instead with shape
        ``(n_samples, n_samples_fitted)``, where ``n_samples_fitted``
        is the number of samples used in the fitting for the estimator.

    y : array-like of shape (n_samples,) or (n_samples, n_outputs)
        True values for `X`.

    sample_weight : array-like of shape (n_samples,), default=None
        Sample weights.

    Returns
    -------
    score : float
        :math:`R^2` of ``self.predict(X)`` wrt. `y`.

    Notes
    -----
    The :math:`R^2` score used when calling ``score`` on a regressor uses
    ``multioutput='uniform_average'`` from version 0.23 to keep consistent
    with default value of :func:`~sklearn.metrics.r2_score`.
    This influences the ``score`` method of all the multioutput
    regressors (except for
    :class:`~sklearn.multioutput.MultiOutputRegressor`).

In [74]:
rf_model.score(X_test_scaled, y_test)

-0.0128069985694792

In [33]:
fire_clean_df2.to_csv("../Resources/fire_clean2.csv")

In [ ]:
def counts(column):
    column=column.value_counts()
    return column.sort_index()

In [ ]:
counts(fire_df.discovery_year)

In [ ]:
counts(fire_df.fire_size)

In [ ]:
counts(fire_df.fire_size_class)

In [ ]:
counts(fire_df.fire_cause)

In [ ]:
counts(fire_df.Temp_pre_30)

In [ ]:
fire_df.columns.to_list()

In [ ]:
raw_df=pd.read_csv("../Resources/FW_Veg_Rem_Combined.csv")
raw_df

In [ ]:
json_df=raw_df.loc[:,"fire_name":"longitude"].drop(["fire_size","stat_cause_descr","fire_size_class"],axis=1).reset_index(drop=True)
json_df

In [ ]:
marker={}
for la in json_df.latitude.values:
    for lo in json_df.longitude.values:
        location=[la,lo]

In [ ]:
location[0:1]

In [ ]:
for name in json_df.fire_name.values:

In [ ]:
json_df.to_csv(r"../Resources/fire.csv")